import type { OrgUnitFormValues } from "./orgUnitForm.types";

export const ORG_UNIT_FORM_INITIAL: OrgUnitFormValues = {
  name: "",
  nameNepali: "",
  code: "",
  unitType: "",
  description: "",
  province: "",
  district: "",
  municipality: "",
  ward: "",
  address: "",
  phone: "",
  email: "",
  fax: "",
  website: "",
  headName: "",
  headTitle: "",
  headPhone: "",
  headEmail: "",
  parentId: "",
  taskVisibility: "all_members",
  confidentialityLevel: "public",
  status: "active",
};
